package app

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/HorizenOfficial/vela-common-go/wasm/types"
)

// commandsFixturePath is generated by sdk/scripts/write-fixtures.mjs from the
// SDK's command builders. See sdkFixtureInputs below for the values it was built
// from — kept here as a second, independent transcription rather than shared
// with the JS side, since a shared source could not have caught either
// implementation drifting from the wire format on its own.
const commandsFixturePath = "../../sdk/test/fixtures/commands.json"

// sdkFixtureInputs mirrors sdk/test/fixture-inputs.mjs by hand.
var sdkFixtureInputs = struct {
	weth, usdc, destination types.Address
	strategyID              string
	intentID                string
	maxOrderBase            types.Uint256
	maxPositionBase         types.Uint256
	allocateAmount          types.Uint256
	redeemShares            types.Uint256
	buyAmount               types.Uint256
	sellAmount              types.Uint256
	withdrawAmount          types.Uint256
	refPrice                types.Uint256
	limitPrice              types.Uint256
	slippageBps             uint32
}{
	strategyID:      "alpha",
	intentID:        "intent-0000000000000001",
	maxOrderBase:    u64(1_000),
	maxPositionBase: u64(5_000),
	allocateAmount:  u64(500_000),
	redeemShares:    u64(400),
	buyAmount:       u64(100),
	sellAmount:      u64(60),
	withdrawAmount:  u64(750),
	slippageBps:     50,
}

func init() {
	sdkFixtureInputs.weth = addr(0xAA)
	sdkFixtureInputs.usdc = addr(0xBB)
	sdkFixtureInputs.destination = addr(0xCC)

	// price() is a test helper (it needs a live *testing.T only to call
	// t.Helper()), so package-level init builds these directly with One().
	ref := One()
	ref.Mul64(3_000)
	sdkFixtureInputs.refPrice = ref

	limit := One()
	limit.Mul64(3_100)
	sdkFixtureInputs.limitPrice = limit
}

type commandsFixture struct {
	Cases []struct {
		Name    string          `json:"name"`
		Command json.RawMessage `json:"command"`
	} `json:"cases"`
}

func loadCommandsFixture(t *testing.T) map[string]json.RawMessage {
	t.Helper()
	raw, err := os.ReadFile(filepath.FromSlash(commandsFixturePath))
	if err != nil {
		t.Fatalf("read fixture: %v (run `npm run fixtures` in sdk/ after changing the wire format)", err)
	}
	var f commandsFixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("fixture has no cases")
	}
	byName := make(map[string]json.RawMessage, len(f.Cases))
	for _, c := range f.Cases {
		byName[c.Name] = c.Command
	}
	return byName
}

// sameAddress reports whether a hex string (any casing — the SDK sends EIP-55
// checksummed addresses, which Address.Hex() does not itself produce) decodes to
// the given address.
func sameAddress(t *testing.T, hexStr string, want types.Address) bool {
	t.Helper()
	got, err := types.HexToAddress(hexStr)
	if err != nil {
		t.Fatalf("not a valid address: %q: %v", hexStr, err)
	}
	return got == want
}

// decodeStrict decodes a command with unknown fields disallowed. Go's default
// decoder silently ignores a field it does not recognise, which would leave the
// corresponding parameter unset rather than fail — exactly the drift this
// fixture exists to catch, so the test must not be as forgiving as production
// code has to be.
func decodeStrict(t *testing.T, raw json.RawMessage, v interface{}) {
	t.Helper()
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.DisallowUnknownFields()
	if err := dec.Decode(v); err != nil {
		t.Fatalf("strict decode: %v\nraw: %s", err, raw)
	}
}

// TestSDKFixtureMatchesGoStructs is the Go half of a cross-language contract
// with the TypeScript SDK, the same pattern used for the trigger's ABI vectors.
// Each side implements the wire format independently; nothing else would stop
// them drifting apart, and a mismatch would otherwise surface only against a
// live enclave, as a command that silently did something other than intended.
func TestSDKFixtureMatchesGoStructs(t *testing.T) {
	in := sdkFixtureInputs
	cases := loadCommandsFixture(t)

	t.Run("register_strategy", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["register_strategy"], &instr)

		if instr.Command != "register_strategy" || instr.RegisterStrategy == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		got := instr.RegisterStrategy
		if got.ID != in.strategyID {
			t.Fatalf("id = %q, want %q", got.ID, in.strategyID)
		}
		wantTokens := []types.Address{in.usdc, in.weth}
		if len(got.Mandate.AllowedTokens) != len(wantTokens) {
			t.Fatalf("allowedTokens = %v, want %v", got.Mandate.AllowedTokens, wantTokens)
		}
		for i, tok := range wantTokens {
			if got.Mandate.AllowedTokens[i] != tok {
				t.Fatalf("allowedTokens[%d] = %s, want %s", i, got.Mandate.AllowedTokens[i].Hex(), tok.Hex())
			}
		}
		if !got.Mandate.MaxOrderBase.Eq(in.maxOrderBase) {
			t.Fatalf("maxOrderBase = %s, want %s", got.Mandate.MaxOrderBase.String(), in.maxOrderBase.String())
		}
		if !got.Mandate.MaxPositionBase.Eq(in.maxPositionBase) {
			t.Fatalf("maxPositionBase = %s, want %s", got.Mandate.MaxPositionBase.String(), in.maxPositionBase.String())
		}
	})

	t.Run("allocate", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["allocate"], &instr)

		if instr.Command != "allocate" || instr.Allocate == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		got := instr.Allocate
		if got.StrategyID != in.strategyID {
			t.Fatalf("strategyId = %q, want %q", got.StrategyID, in.strategyID)
		}
		if !got.Amount.Eq(in.allocateAmount) {
			t.Fatalf("amount = %s, want %s", got.Amount.String(), in.allocateAmount.String())
		}
		// PriceSet keys canonicalise to Address.Hex(), which is why the SDK
		// checksums addresses before sending: this proves the two normalise to
		// the same key rather than silently failing to look the price up.
		price, ok := got.Prices.Price(in.weth, in.usdc)
		if !ok || !price.Eq(price) {
			t.Fatalf("price for weth not found under the checksummed key: %v", got.Prices)
		}
	})

	t.Run("redeem", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["redeem"], &instr)

		if instr.Command != "redeem" || instr.Redeem == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		got := instr.Redeem
		if got.StrategyID != in.strategyID {
			t.Fatalf("strategyId = %q, want %q", got.StrategyID, in.strategyID)
		}
		if !got.Shares.Eq(in.redeemShares) {
			t.Fatalf("shares = %s, want %s", got.Shares.String(), in.redeemShares.String())
		}
		if len(got.Prices) != 0 {
			t.Fatalf("expected no prices, got %v", got.Prices)
		}
	})

	t.Run("submit_intent buy requires a limit price", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["submit_intent_buy"], &instr)

		if instr.Command != "submit_intent" || instr.Intent == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		got := instr.Intent
		// The SDK sends EIP-55 checksummed addresses; Address.Hex() does not
		// produce that casing, so tokens are compared by decoded value.
		if got.StrategyID != in.strategyID || !sameAddress(t, got.Base, in.weth) {
			t.Fatalf("unexpected intent target: %+v", got)
		}
		if got.Side != SideBuy {
			t.Fatalf("side = %v, want buy", got.Side)
		}
		if !got.Amount.Eq(in.buyAmount) {
			t.Fatalf("amount = %s, want %s", got.Amount.String(), in.buyAmount.String())
		}
		if got.LimitPrice == nil || got.LimitPrice.IsZero() {
			t.Fatal("the SDK must refuse to build a buy without a limit price; this must never be zero")
		}
		if !got.LimitPrice.Eq(in.limitPrice) {
			t.Fatalf("limitPrice = %s, want %s", got.LimitPrice.String(), in.limitPrice.String())
		}
	})

	t.Run("submit_intent sell may be unconditional", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["submit_intent_sell_unconditional"], &instr)

		got := instr.Intent
		if got == nil || got.Side != SideSell {
			t.Fatalf("unexpected: %+v", got)
		}
		if !got.Amount.Eq(in.sellAmount) {
			t.Fatalf("amount = %s, want %s", got.Amount.String(), in.sellAmount.String())
		}
		if got.LimitPrice == nil || !got.LimitPrice.IsZero() {
			t.Fatalf("an omitted limit price must decode as zero, got %v", got.LimitPrice)
		}
	})

	t.Run("cancel_intent", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["cancel_intent"], &instr)

		if instr.Command != "cancel_intent" || instr.CancelIntent == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		if instr.CancelIntent.IntentID != in.intentID {
			t.Fatalf("intentId = %q, want %q", instr.CancelIntent.IntentID, in.intentID)
		}
	})

	t.Run("close_batch names the pair explicitly", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["close_batch"], &instr)

		if instr.Command != "close_batch" || instr.CloseBatch == nil {
			t.Fatalf("unexpected: %+v", instr)
		}
		got := instr.CloseBatch
		if !sameAddress(t, got.Base, in.weth) {
			t.Fatalf("base = %q, does not decode to %s", got.Base, in.weth.Hex())
		}
		if !got.RefPrice.Eq(in.refPrice) {
			t.Fatalf("refPrice = %s, want %s", got.RefPrice.String(), in.refPrice.String())
		}
		if got.SlippageBps != in.slippageBps {
			t.Fatalf("slippageBps = %d, want %d", got.SlippageBps, in.slippageBps)
		}
	})

	t.Run("withdraw to an explicit destination", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["withdraw_to_destination"], &instr)

		got := instr.Withdraw
		if got == nil || !sameAddress(t, got.Token, in.usdc) {
			t.Fatalf("unexpected: %+v", got)
		}
		if !got.Amount.Eq(in.withdrawAmount) {
			t.Fatalf("amount = %s, want %s", got.Amount.String(), in.withdrawAmount.String())
		}
		if !sameAddress(t, got.Destination, in.destination) {
			t.Fatalf("destination = %q, does not decode to %s", got.Destination, in.destination.Hex())
		}
	})

	// The SDK omits an unset destination rather than sending an empty string, so
	// it must default the same way an unsent field does: to the sender.
	t.Run("withdraw with no destination omits the field", func(t *testing.T) {
		var instr PayloadInstructions
		decodeStrict(t, cases["withdraw_to_sender"], &instr)

		got := instr.Withdraw
		if got == nil {
			t.Fatal("missing withdraw")
		}
		if got.Destination != "" {
			t.Fatalf("destination = %q, want the field omitted (empty)", got.Destination)
		}
	})
}

// TestSDKFixtureEndToEnd feeds fixture commands through the real handlers
// against the same harness the rest of this package uses, so a case that
// decodes correctly but the app still refuses is caught here rather than only
// against a live stack. The harness's quote token and the fixture's usdc are
// the same address (addr(0xBB)), which is what lets the two interoperate at all.
func TestSDKFixtureEndToEnd(t *testing.T) {
	cases := loadCommandsFixture(t)
	h := newHarness(t)
	manager := addr(0x21)

	submit := func(t *testing.T, sender types.Address, name string) Receipt {
		t.Helper()
		raw, ok := cases[name]
		if !ok {
			t.Fatalf("fixture is missing case %q", name)
		}
		padded, err := PadPayload(raw)
		if err != nil {
			t.Fatalf("%s: PadPayload: %v", name, err)
		}
		res := ProcessRequest(&sender, RequestTypeProcess, string(padded), h.state)
		if res.Error != "" {
			t.Fatalf("%s: public error: %s", name, res.Error)
		}
		h.state = string(res.State)
		if len(res.Events) == 0 {
			t.Fatalf("%s: expected at least a receipt event", name)
		}
		var receipt Receipt
		if err := json.Unmarshal(bytes.TrimRight(res.Events[0].Data, " "), &receipt); err != nil {
			t.Fatalf("%s: unmarshal receipt: %v", name, err)
		}
		return receipt
	}

	if r := submit(t, manager, "register_strategy"); r.Status != statusAccepted {
		t.Fatalf("register_strategy was rejected: %s", r.Reason)
	}

	// Fund the strategy directly, standing in for positions acquired by earlier
	// trading, so the buy the fixture describes can actually be afforded.
	h.fund("alpha", tokenUSDC, 1_000_000)

	buyReceipt := submit(t, manager, "submit_intent_buy")
	if buyReceipt.Status != statusAccepted {
		t.Fatalf("submit_intent_buy was rejected: %s", buyReceipt.Reason)
	}

	// Intent IDs are derived from a counter (deterministicID in ledger.go), not
	// randomness, and this is the first intent ever submitted against this fresh
	// state. The fixture's intentId was fixed independently in
	// fixture-inputs.mjs, but happens to be exactly that first ID — which turns
	// this into a real assertion rather than only a decode check: cancel_intent
	// must remove precisely the intent submit_intent_buy just created.
	wantID := buyReceipt.Detail["intentId"]
	if wantID != sdkFixtureInputs.intentID {
		t.Fatalf("test assumption broken: first intent id = %q, fixture intentId = %q — "+
			"update fixture-inputs.mjs's intentId to match, or stop relying on the coincidence",
			wantID, sdkFixtureInputs.intentID)
	}

	if r := submit(t, manager, "cancel_intent"); r.Status != statusAccepted {
		t.Fatalf("cancel_intent was rejected: %s", r.Reason)
	}

	st := h.load()
	if len(st.Pending) != 0 {
		t.Fatalf("pending intents = %d after cancelling the only one, want 0", len(st.Pending))
	}
}
